In [59]:
import sys
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))

from src.extract import read_csv
from src.cleaning import clean_netflix
from src.feature_engineering import (
    create_rating_group,
    create_main_country,
    create_continent,
    create_language,
    create_date_features,
    create_genre,
)

df = read_csv('../data/netflix_titles.csv')

df = clean_netflix(df)

df = create_rating_group(df)
df = create_main_country(df)
df = create_continent(df)
df = create_language(df)
df = create_date_features(df)
df = create_genre(df)

df.head()

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,rating_group,main_country,continent,language,year_added,delay_added,genre
0,Movie,Dick Johnson Is Dead,Kirsten Johnson,Not Informed,United States,2021-09-25,2020,PG-13,90,Documentaries,"As her father nears the end of his life, filmm...",Teen,United States,North America,English,2021,1,Documentary
1,TV Show,Blood & Water,Not Informed,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",Adult,South Africa,Africa,Zulu,2021,0,International
2,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,1,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,Adult,Unknown,Unknown,Unknown,2021,0,Crime
3,TV Show,Jailbirds New Orleans,Not Informed,Not Informed,Unknown,2021-09-24,2021,TV-MA,1,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",Adult,Unknown,Unknown,Unknown,2021,0,Documentary
4,TV Show,Kota Factory,Not Informed,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,Adult,India,Asia,Hindi,2021,0,International

In [53]:
df.delay_added.value_counts().reset_index()

    delay_added  count
0             0   3241
1             1   1585
2             2    714
3             3    491
4             4    367
..          ...    ...
70           93      1
71           -2      1
72           63      1
73           -3      1
74           70      1

[75 rows x 2 columns]

In [55]:
df[df['delay_added']<0].sort_values('delay_added')

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,rating_group,main_country,continent,year_added,delay_added,genre
7112,TV Show,Jack Taylor,Stuart Orme,"Iain Glen, Killian Scott, Nora-Jane Noone, Tar...","United States, Ireland",2013-03-31,2016,TV-MA,1,"Crime TV Shows, International TV Shows, TV Dramas",Ken Bruen's bestselling crime novels leap to l...,Adult,United States,North America,2013,-3,Crime
5658,TV Show,Sense8,Not Informed,"Tuppence Middleton, Brian J. Smith, Doona Bae,...",United States,2016-12-23,2018,TV-MA,2,"Crime TV Shows, TV Dramas, TV Mysteries","From the creators of ""The Matrix"" and ""Babylon...",Adult,United States,North America,2016,-2,Crime
1551,TV Show,Hilda,Not Informed,"Bella Ramsey, Ameerah Falzon-Ojo, Oliver Nelso...","United Kingdom, Canada, United States",2020-12-14,2021,TV-Y7,2,Kids' TV,"Fearless, free-spirited Hilda finds new friend...",Kids,United Kingdom,Europe,2020,-1,Family
1696,TV Show,Polly Pocket,Not Informed,"Emily Tennant, Shannon Chan-Kent, Kazumi Evans...","Canada, United States, Ireland",2020-11-15,2021,TV-Y,2,Kids' TV,After uncovering a magical locket that allows ...,Kids,Canada,North America,2020,-1,Family
3287,TV Show,Maradona in Mexico,Not Informed,Diego Armando Maradona,"Argentina, United States, Mexico",2019-11-13,2020,TV-MA,1,"Docuseries, Spanish-Language TV Shows","In this docuseries, soccer great Diego Maradon...",Adult,Argentina,South America,2019,-1,Documentary
3369,TV Show,BoJack Horseman,Not Informed,"Will Arnett, Aaron Paul, Amy Sedaris, Alison B...",United States,2019-10-25,2020,TV-MA,6,TV Comedies,Meet the most beloved sitcom horse of the '90s...,Adult,United States,North America,2019,-1,Comedy
2920,TV Show,Love Is Blind,Not Informed,"Nick Lachey, Vanessa Lachey",United States,2020-02-13,2021,TV-MA,1,"Reality TV, Romantic TV Shows",Nick and Vanessa Lachey host this social exper...,Adult,United States,North America,2020,-1,Reality
3168,TV Show,Fuller House,Not Informed,"Candace Cameron Bure, Jodie Sweetin, Andrea Ba...",United States,2019-12-06,2020,TV-PG,5,TV Comedies,The Tanner family’s adventures continue as DJ ...,Teen,United States,North America,2019,-1,Comedy
4844,TV Show,Unbreakable Kimmy Schmidt,Not Informed,"Ellie Kemper, Jane Krakowski, Tituss Burgess, ...",United States,2018-05-30,2019,TV-14,4,TV Comedies,When a woman is rescued from a doomsday cult a...,Teen,United States,North America,2018,-1,Comedy
3433,TV Show,The Hook Up Plan,Not Informed,"Marc Ruchmann, Zita Hanrot, Sabrina Ouazani, J...",France,2019-10-11,2020,TV-MA,2,"International TV Shows, Romantic TV Shows, TV ...","When Parisian Elsa gets hung up on her ex, her...",Adult,France,Europe,2019,-1,International
5394,Movie,Hans Teeuwen: Real Rancour,Doesjka van Hoogdalem,Hans Teeuwen,Netherlands,2017-07-01,2018,TV-MA,86,Stand-Up Comedy,Comedian Hans Teeuwen rebels against political...,Adult,Netherlands,Europe,2017,-1,Comedy
4845,TV Show,Arrested Development,Not Informed,"Jason Bateman, Portia de Rossi, Will Arnett, M...",United States,2018-05-29,2019,TV-MA,5,TV Comedies,It's the Emmy-winning story of a wealthy famil...,Adult,United States,North America,2018,-1,Comedy
5677,TV Show,Tokyo Trial,Not Informed,"Marcel Hensema, Paul Freeman, Irrfan Khan, Sta...","Canada, Japan, Netherlands",2016-12-13,2017,TV-MA,1,"International TV Shows, TV Dramas","In the wake of World War II, 11 Allied judges ...",Adult,Canada,North America,2016,-1,International
7063,Movie,Incoming,Eric Zaragosa,"Scott Adkins, Aaron McCusker, Vahldin Prelic, ...","Serbia, United States",2018-10-26,2019,TV-MA,89,"Action & Adventure, Sci-Fi & Fantasy",When an imprisoned terrorist cell hijacks a hi...,Adult,Serbia,Europe,2018,-1,Action & Adventure

In [58]:
import importlib
import src.feature_engineering as fe

importlib.reload(fe)

print(dir(fe))

['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'create_continent', 'create_date_features', 'create_genre', 'create_language', 'create_main_country', 'create_rating_group', 'pd']

In [12]:
import sys

!{sys.executable} -m pip freeze > ../requirements.txt